const content = window.APP_CONTENT;
const tabButtons = [...document.querySelectorAll("[data-tab]")];
const panels = [...document.querySelectorAll("[data-panel]")];
const pageHeading = document.querySelector("#page-heading");
const tabTitles = {lessons:"Μαθήματα",quiz:"Quiz",visualizers:"Visualizers",results:"Αποτελέσματα"};
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function activateTab(tab){tabButtons.forEach(btn=>btn.classList.toggle("active",btn.dataset.tab===tab));panels.forEach(panel=>panel.classList.toggle("active",panel.dataset.panel===tab));pageHeading.textContent=tabTitles[tab]||"Μαθήματα";history.replaceState(null,"",`#${tab}`);}
tabButtons.forEach(btn=>btn.addEventListener("click",()=>activateTab(btn.dataset.tab)));
function renderLessons(){const grid=document.querySelector("#lesson-grid");const readyCount=content.lessons.filter(x=>x.status==="ready").length;document.querySelector("#lesson-counter").textContent=`${readyCount} ενεργές / ${content.lessons.length} ενότητες`;grid.innerHTML="";content.lessons.forEach(lesson=>{const a=document.createElement("a");a.className=`modern-lesson-card ${lesson.status==="ready"?"ready":"planned"}`;a.href=`lesson.html?id=${lesson.id}`;const tags=lesson.tags.slice(0,2).map(tag=>`<span>${escapeHtml(tag)}</span>`).join("");a.innerHTML=`<div class="modern-number">${lesson.id}</div><div class="modern-lesson-text"><span class="modern-group">${escapeHtml(lesson.group)}</span><strong>${escapeHtml(lesson.title)}</strong><div class="modern-tags">${tags}</div></div><div class="lesson-arrow">→</div>`;grid.appendChild(a);});}
function renderQuiz(){const host=document.querySelector("#quiz-grid");host.innerHTML=content.quizCards.map(card=>`<a class="modern-tool-card" href="${card.href}"><div class="tool-card-top"><span class="modern-tool-icon">?</span><span class="status-pill">${escapeHtml(card.badge)}</span></div><strong>${escapeHtml(card.title)}</strong><p>${escapeHtml(card.description)}</p><span class="open-link">Άνοιγμα Quiz →</span></a>`).join("");}
function renderVisualizers(){const host=document.querySelector("#visualizer-grid");host.innerHTML=content.visualizers.map((card,index)=>`<a class="modern-tool-card" href="${card.href}"><div class="tool-card-top"><span class="modern-tool-icon">${index+1}</span><span class="status-pill neutral">Interactive</span></div><strong>${escapeHtml(card.title)}</strong><p>${escapeHtml(card.description)}</p><span class="open-link">Άνοιγμα Visualizer →</span></a>`).join("");}
renderLessons();renderQuiz();renderVisualizers();const initial=location.hash.replace("#","")||"lessons";activateTab(["lessons","quiz","visualizers","results"].includes(initial)?initial:"lessons");